version: "3"

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./db/:/my/sqlite/path/
    command: python3 main.py

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  server:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "8081:8081"
    command: telegram-bot-api --api-id=${TELEGRAM_API_ID} --api-hash=${TELEGRAM_API_HASH}