version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./db/:/my/sqlite/path/

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
